### ISSUE TITLE
June Release Roadmap

### ISSUE THREAD

**Issue by codestar12** [txst-per-group/Glowscript-Blocks#40]
- [x] implement graphs
- [x] create scene colorblock #34 
- [x] use glowscript syntax for math blocks #35 
- [x] recategorize math blocks #36 
- [x] add our "custom" attributes to shape constructor blocks #37
